// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[RawText-1]
	_ = x[Return-2]
	_ = x[EndOpcode-3]
}

const _Opcode_name = "NopRawTextReturnEndOpcode"

var _Opcode_index = [...]uint8{0, 3, 10, 16, 25}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
